# Generated by Django 5.1.6 on 2025-02-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('valor', models.FloatField()),
                ('foto', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['data_criacao'],
            },
        ),
    ]
